CREATE TABLE exoplanets (
    pl_name TEXT,
    hostname TEXT,
    sy_snum TEXT,
    sy_pnum TEXT,
    discoverymethod TEXT,
    disc_year TEXT,
    disc_facility TEXT,
    pl_controv_flag TEXT,
    pl_orbper TEXT,
    pl_orbpererr1 TEXT,
    pl_orbpererr2 TEXT,
    pl_orbperlim TEXT,
    pl_orbsmax TEXT,
    pl_orbsmaxerr1 TEXT,
    pl_orbsmaxerr2 TEXT,
    pl_orbsmaxlim TEXT,
    pl_rade TEXT,
    pl_radeerr1 TEXT,
    pl_radeerr2 TEXT,
    pl_radelim TEXT,
    pl_radj TEXT,
    pl_radjerr1 TEXT,
    pl_radjerr2 TEXT,
    pl_radjlim TEXT,
    pl_bmasse TEXT,
    pl_bmasseerr1 TEXT,
    pl_bmasseerr2 TEXT,
    pl_bmasselim TEXT,
    pl_bmassj TEXT,
    pl_bmassjerr1 TEXT,
    pl_bmassjerr2 TEXT,
    pl_bmassjlim TEXT,
    pl_bmassprov TEXT,
    pl_orbeccen TEXT,
    pl_orbeccenerr1 TEXT,
    pl_orbeccenerr2 TEXT,
    pl_orbeccenlim TEXT,
    pl_eqt TEXT,
    pl_eqterr1 TEXT,
    pl_eqterr2 TEXT,
    pl_eqtlim TEXT,
    st_spectype TEXT,
    st_teff TEXT,
    st_tefferr1 TEXT,
    st_tefferr2 TEXT,
    st_tefflim TEXT,
    st_rad TEXT,
    st_raderr1 TEXT,
    st_raderr2 TEXT,
    st_radlim TEXT,
    st_mass TEXT,
    st_masserr1 TEXT,
    st_masserr2 TEXT,
    st_masslim TEXT,
    st_met TEXT,
    st_meterr1 TEXT,
    st_meterr2 TEXT,
    st_metlim TEXT,
    st_metratio TEXT,
    rastr TEXT,
    ra TEXT,
    decstr TEXT,
    decl TEXT,
    sy_dist TEXT,
    sy_disterr1 TEXT,
    sy_disterr2 TEXT,
    sy_vmag TEXT,
    sy_vmagerr1 TEXT,
    sy_vmagerr2 TEXT,
    sy_kmag TEXT,
    sy_kmagerr1 TEXT,
    sy_kmagerr2 TEXT,
    sy_gaiamag TEXT,
    sy_gaiamagerr1 TEXT,
    sy_gaiamagerr2 TEXT
);

LOAD DATA LOCAL INFILE 'C:/Users/Akshay/Documents/Project_work/Exoplanet-Trends-Project/Data/PSCompPars_2025.06.18_07.30.56.csv'
INTO TABLE exoplanets
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 84 LINES;

SET GLOBAL local_infile = 1;

SELECT *
FROM exoplanets;